version: '3'
services:
  note-backend:
    build:
      dockerfile: Dockerfile
    container_name: noteBackend
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: "/app/configs/docker.yaml"
      APP_PROFILE: "docker"
    restart: unless-stopped
    networks:
      - skynet
    depends_on:
      - postgres_server

  postgres_server:
    container_name: postgresServer
    restart: always
    image: postgres:14
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./data/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - skynet

networks:
  skynet:




