openapi: 3.0.1
info:
  title: Note application API
  version: '1.0.0'
servers:
  - url: 'http://localhost:8080'
    description: local

paths:
  /note:
    post:
      tags:
        - Note
      operationId: saveNote
      description: 'Сохранить записку'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNoteRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleNoteBackendResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
#--------------------------------------------------------------------------------------------------------#
  /note/{id}:
    get:
      tags:
        - Note
      operationId: getNotesById
      description: 'Взять записку по id'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleNoteBackendResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
#--------------------------------------------------------------------------------------------------------#
components:
  responses:
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackendErrorResponse'
    '401':
      description: UNAUTHORIZED
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackendErrorResponse'
    404:
      description: NOT_FOUND
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackendErrorResponse'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackendErrorResponse'
#--------------------------------------------------------------------------------------------------------#
  schemas:
    BackendErrorResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/MetaData'
        errorCode:
          type: integer
        description:
          type: string
#--------------------------------------------------------------------------------------------------------#
    MetaData:
      type: object
      properties:
        timestamp:
          type: string
        path:
          type: string
#--------------------------------------------------------------------------------------------------------#
    BasicBackendResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/MetaData'
        errorCode:
          type: string
        description:
          type: string
#--------------------------------------------------------------------------------------------------------#
    CreateNoteRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        link:
          type: string
#--------------------------------------------------------------------------------------------------------#
    NoteResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          x-go-type: uint
        name:
          type: string
        link:
          type: string
        description:
          type: string
#--------------------------------------------------------------------------------------------------------#
    SingleNoteBackendResponse:
      allOf:
        - $ref: '#/components/schemas/BasicBackendResponse'
        - type: object
          properties:
            payload:
              $ref: '#/components/schemas/NoteResponse'
    ListNoteBackendResponse:
      allOf:
        - $ref: '#/components/schemas/BasicBackendResponse'
        - type: object
          properties:
            payload:
              type: array
              items:
                $ref: '#/components/schemas/NoteResponse'
#--------------------------------------------------------------------------------------------------------#